theme: jekyll-theme-cayman
title: [Perfect DeepBlue]
description: [Passion project to build a pretty - enthusiast computer which will be future proof for next 6 years, with no noticable performance problems for it's expected lifetime]